title: Greatest page ever
theme: minima
author: scothers0
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
A starting github pages thing for use when I actually need to host a proper site.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
